dist: trusty
sudo: false

before_install: gem update bundler
cache: bundler

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - rbx
  - jruby-9
  - jruby-head

matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby-head
  fast_finish: true

script: bundle exec rspec spec
